### ISSUE TITLE
Incompatible with Nim 1.*

### ISSUE THREAD

**Issue by Guevara-chan** [emekoi/suffer#1]
Compiler said me so:
`suffer-0.1.2\suffer.nim(53, 3) Error: union type may not be packed.`

**Comment by Guevara-chan** [comment]
Hey, hey, hey ! Looks like I fixed your incompatibilities. Wanna look ?

**Comment by emekoi** [comment]
sorry, about that. i stopped using nim quite some time ago and i didn't see any notification from github about this issue.
